sensor:
  - platform: tibber
    access_token: 54c441f83f5c80f86b6ad4dc34709afb9c07d0dc2db41a187370dbd9e1b4a718


  - platform: template
    sensors:
      percentpower:
        friendly_name: "av Maks"
        unit_of_measurement: '%'
        value_template: "{{ states.input_number.currentpriceinp.state }}"
        
 
light:
  platform: limitlessled
  bridges:
    - host: 192.168.1.95
      groups:
      - number: 1
        name: powerstrip
        type: rgbw
        
# Variabler for kalkulering av prosentpris strom       


input_number:
  currentpriceinp:
    name: Prosent av maks
    initial: 0
    min: 0
    max: 100
    step: 0.001
    mode: box
  1poffprice:
    name: En prosent
    initial: 0
    min: 0
    max: 100
    step: 0.001
    mode: box
    
  g_intensity:
    name: G
    initial: 0
    min: 0
    max: 255
    step: 1
    mode: slider
    
  r_intensity:
    name: R
    initial: 0
    min: 0
    max: 255
    step: 1
    mode: slider
    
  brightness_pwstrip:
    name: Dimming prisstrips
    min: 0
    max: 255
    step: 1
    mode: slider


    
input_boolean:
  playsonostest:
    name: les opp pris
    
